config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'core#home'
  get '/home', to: 'core#home' 
  get '/ranking', to: 'core#ranking', as: 'ranking'
  get '/detail/:id', to: 'core#detail', as: 'detail'

  resources :like, only: [:create, :destroy] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :api_key, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
require 'swapi'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
    before_action :authenticate_user!

    def home
      begin
        @movies = Swapi.fetchAll        
      rescue Net::ReadTimeout => e
        puts e.message
        # register error
      end
      @likes = {} 
      current_user.likes.as_json.map { |x| @likes[x["api_key"]] = x }
    end
    
    def ranking
      begin
        @movies = {}
        Swapi.fetchAll["results"].as_json.map { |x| @movies[x["episode_id"]] = x }
        @votes = Like.select("likes.api_key, max(created_at) as data, count(*) as votos"
                        ).group("likes.api_key").order("votos desc"
                        ).order("data desc").as_json.map{ |x| x }
      rescue Net::ReadTimeout => e
        puts e.message
        # register error
      end       
    end
    
    def detail
      begin
        @details = Swapi.fetchDetail(det_params)
      rescue Net::ReadTimeout => e
        puts e.message
        # register error
      end
    end

    private
    def det_params
      params.require(:id)
    end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
    before_action :authenticate_user!

    def create
        if current_user.likes.count < 2
            @like = current_user.likes.new(like_params)
            @like.save
            respond_to do |format|
                format.js 
            end
        else
            respond_to do |format|
                format.js {
                    render "error"
                }
            end
        end
    end

    def destroy
        @like = current_user.likes.where("api_key": like_destroy_params).first
        @like.destroy
        respond_to do |format| 
            format.js 
        end
    end

    private
        def like_params
            params.require(:like).permit(:api_key)
        end

        def like_destroy_params
            params.require(:id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/views/application/home.html.erb
<br>

<table class="table table-striped table-bordered">
  <tr class="text-center thead-light">
    <th>Nome do Filme</th>
    <th>Episódio</th>
    <th>Diretor</th>
    <th>Ano</th>
  </tr>
  <% @movies["results"].each_with_index do |item, index| %>
    <%= render partial: 'application/table', locals: { item: item,  index: index} %>
  <% end %>
</table>

 
    
  

app/views/core/_table.html.erb
<tr>
  <td><%= item["title"] %></td> 
  <td><%= item["episode_id"] %></td> 
  <td><%= item["director"] %></td> 
  <td class="text-center"><%= item["release_date"].to_date.strftime("%Y") %></td> 
  <td class="text-center"> 
    <% if @likes.include? item["episode_id"] %>
        <%= render partial: 'like/unlike', locals: { id: item["episode_id"]} %>      
    <% else %>        
        <%= render partial: 'like/like', locals: { id: item["episode_id"]} %>
    <% end %>
  </td>
</tr>

app/views/core/_table_ranking.html.erb
<tr>
  <td class="text-center"> <%= index + 1 %></td> 
  <td>
    <% if index < 2 %>
      <%= link_to "#{movie[vote["api_key"]]["title"]}", detail_path(id: movie[vote["api_key"]]["url"].match('\/(?:\w{5})\/(\d+)\/')[1] ) %> 
    <% else %>
      <%= movie[vote["api_key"]]["title"]  %>
    <% end %>
  </td> 
  <td><%= vote["api_key"] %></td> 
  <td><%= movie[vote["api_key"]]["director"]  %></td> 
  <td><%= movie[vote["api_key"]]["release_date"].to_date.strftime("%Y")  %></td> 
  <td><%= vote["votos"] %></td> 
</tr>

app/views/core/detail.html.erb
<br>
<% if @details.nil? %>
  <tr class="text-center">
    <td colspan="6">
      <strong>Api de dados fora do ar.</strong>
    </td>
  </tr>
<% else %>
  <div class="container text-left">
    <div class="card">
      <div class="card-body text left">
        <h4 class="card-title"><%= @details["title"] %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><strong>Director:</strong> <%= @details["director"] %></h6>
        <h6 class="card-subtitle mb-2 text-muted"><strong>Produtor:</strong> <%= @details["producer"] %></h6>

        <p class="card-text"><strong>Episodio:</strong>  <%= @details["episode_id"] %> Episode <%= @details["title"] %> </p>
        <p class="card-text"><strong>Resenha:</strong> <%= @details["opening_crawl"] %> </p>
      </div>
    </div>
  </div>
<% end %>

app/views/core/home.html.erb
<br>

<table class="table table-striped table-bordered">
  <tr class="text-center thead-light">
    <th>Nome do Filme</th>
    <th>Episódio</th>
    <th>Diretor</th>
    <th>Ano</th>
    <th></th>
  </tr>

  <% if @movies.nil? %>
    <tr class="text-center">
      <td colspan="6">
        <strong>Api de dados fora do ar.</strong>
      </td>
    </tr>
  <% else %>
    <% @movies["results"].each do |item| %>
      <%= render partial: 'core/table', locals: { item: item,  likes: @likes} %>
    <% end %>
  <% end %>
</table>



<div id="myModal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Favoritos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Você não pode favoritar mais que dois filmes.</p>
      </div>
    </div>
  </div>
</div>

app/views/core/ranking.html.erb
<br>

<table class="table table-striped table-bordered">
  <tr class="text-center thead-light">
    <th>#</th>
    <th>Nome do Filme</th>
    <th>Episódio</th>
    <th>Diretor</th>
    <th>Ano</th>
    <th>Votos</th>
  </tr>
  
  <% if @votes.nil? %>
    <tr class="text-center">
      <td colspan="6">
        <strong>Api de dados fora do ar.</strong>
      </td>
    </tr>
  <% else %>
      <% @votes.each_with_index do |vote, index| %>
        <%= render partial: 'core/table_ranking', locals: { vote: vote,  index: index, movie: @movies}  %>
      <% end %>
  <% end %>
</table>

<small>* No caso de empate a data dos votos é usado como quesito para desempate, ficando em primeiro aquele que atingiu a quantidade de votos primeiro.</small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">      
            <strong><%= current_user.email %> </strong>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary'  %>
        </div>
      </nav>
      <br>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light  ">
          <div class="navbar-nav">
            <div class="nav-item">
              <%= link_to 'Home', home_path, class: "nav-link" %>
            </div>
            <div class="nav-item">
              <%= link_to 'Ranking', ranking_path, class: " nav-link" %>
            </div>
          </div>
        </nav>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>  
    <div class="container ">
      <%= yield %>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/like/_like.html.erb
<%= link_to "", 
  like_index_path, 
  id: "#{id}",
  data: { method: :post, 
          remote: true, 
          params: { like: { api_key: id }}.to_param },
  class: 'fa fa-heart-o text-danger'%>

app/views/like/_unlike.html.erb
<%= link_to "", 
      like_path(id: id),
      method: :delete, 
      remote: true,
      id: "#{id}",
      class: 'fa fa-heart text-danger'%>

app/views/like/create.js.erb
<%= j id = params["like"]["api_key"] %>
$('#'+<%= j id  %>).parent().html('<%= j render partial: 'unlike', :locals => {:id => id }  %>');

app/views/like/destroy.js.erb
<% j id=  params["id"]  %>
console.log('destroy');
$('#'+<%= j id  %>).parent().html('<%= j render partial: 'like', :locals => {:id => id }  %>');

app/views/like/error.js.erb
$('#myModal').modal('show');